### PR TITLE
SSG / SSR fixes & some performance improvements

### LINKED ISSUE #96: SEO, performance & accessibility improvements
I analyzed the Agora app too in terms of SEO/performance/accessibility, and made a list of the recommended improvements:

**SEO**
- [x] We should add meta description to the pages
- [x] Add title tag on the community page
- [x] ❗ It seems like the community page isn't server side rendered, I think it would be a good idea to render the most important data (like community name, description, etc.) that way - we could also use this data to populate meta tags on this page!

*Note: I see that we're fetching data in `getStaticProps`, so I'm not sure why the page isn't rendered server side. Any ideas?* 🤔 

**Performance**
- [x] We should properly size images in the app too - we can set an explicit width & height to them, and we could also use properly scaled images (if possible). Since we're loading a lot of images on the front page, this might improve the initial load speed a lot.
- [ ] ~~Maybe we should add lazy loading to the community logo images (on the front page, where we list the communities)?~~ *Note: it isn't necessary now, since we're displaying images in a smaller scale. We could use the Next.js Image component, but that would generate optimized images on Vercel, and wouldn't fetch images every time from the AWS S3 servers*
- [ ] ~~Longer cache lifetime can also improve performance, so we could use longer cache expiration time where possible (e.g. for images which won't change frequently) - [link](https://web.dev/uses-long-cache-ttl/)~~ *Note: right now most of the images are fetched from coingecko, so we can't really modify this...*

**Accessibility**
- [x] Headings aren't in the right order, we don't have h3 tag on the front page, but we have h2 and h4 tags.
- [x] We should add `alt` attribute to the community logo on the community page

**Best practices**
- [x] We should add `rel="noopener"` or `rel="noreferrer"` to external links (e.g. in the dropdown menu below the logo)

~~**Optional**~~ *Note: will be added in a separate PR*
- [ ] Add ~~[Google Analytics](https://analytics.google.com/) & [Microsoft Clarity](https://clarity.microsoft.com/)~~ or maybe [Plausible](https://plausible.io/) (?) to the site, so we can analyze how users interact with our website

### PR DESCRIPTION
**Pull request by cs-balazs**
Closes #96

### CODE REVIEW

**Comment by cs-balazs** [comment]
I think I managed to fix the static generation problems of the community page.
Things I have changed:
  - The problem seemed to be caused by the `Portal` in `CommunityProvider`, so I changed it to only use it on the client side.
  - A similar problem was with `useWindowSize`, so added some conditions to have a default window size when not on the client side.
  - Removed the `CommunityProvider` from `[community]/index.tsx`, right now nothing seemed to use it.

Some refactors that I originally thought would help, and didn't, but left them there because I like them:
  - Added initial data to `useMemberCount`, and moved the logic of `useMemo` to the fetcher. (I'm not sure about the initial data, don't like the fact that it needs the second parameter, I'll try to find another solution)
  - Changed `useColorPalette` to use `useMemo`, and moved some constant values to a separate file, so they are not computed when `useMemo` (or previously `useEffect`) triggers.

File: src/pages/[community]/index.tsx [hunk 1]
```diff
@@ -12,30 +11,28 @@ type Props = {
 }
 
 const CommunityPage = ({ communityData }: Props): JSX.Element => (
-  <CommunityProvider data={communityData}>
```
Comment (KovJonas) [inline src/pages/[community]/index.tsx:15]: I think we used the `CommunityProvider` to display the color gradient background for the community page (e.g. check the difference between the `/agora/` and `/agora/community` pages), so it would be great if we could keep it.

**Review by KovJonas — CHANGES_REQUESTED** [review]
I like these changes that you made, but I think we should keep the `CommunityProvider` in `src/pages/[community]/index.tsx`.

File: src/pages/[community]/index.tsx (hunk 1 above)
Comment (cs-balazs) [reply src/pages/[community]/index.tsx:15]: You are absolutely right, I forgot about that! I didn't find any `useCommunity` calls, and didn't find any, that's why I thought its unnecessary.

**Comment by dovalid** [comment]
The linked issue has a lot of stuff, this PR has a complete fix for the SSG problem so I've renamed it accordingly and will merge it now. We should create other PR(s) for the remaining points in the issue

**Review by dovalid — APPROVED** [review]

**Review by KovJonas — APPROVED** [review]
