### PR TITLE
Small fixes, refactors

### LINKED ISSUE #88: Fix bugs, improve typing

### PR DESCRIPTION
**Pull request by cs-balazs**
Closes #88 

This branch is quite a mess, but these changes felt way too small to have a separate issue, branch, and PR for them.
The changes I have made so far (including some, that came up today on discord):
  - Tried to fix the wallet connection problem when the user gets redirected from the discord auth site. Couldn't fully solve this, but at least right now the button isn't just loading, but asking for a wallet connection.
  - Some minor fixes in the dc join machine, the error states weren't correctly handled on the presentational side.
  - The network connection modal now closes after a correct network has been selected.
  - Polygon was still hardcoded when categorizing the community cards in the explorer, also the current chain data .find() was incorrect. Right now on the prod deploy Ethane shows up as "your community" when Matic is selected, this is what I wanted to (and I think did) solve here.
  - As Bruno and Tomi suggested, I changed the join modal success states, so that the footer button is the invite link. (Might be a bad solution in terms of accessibility, wasn't sure about that)
  - Refactored the common/Link component, so we don't need to destructure Link when importing (the type that was previously exported was not used anywhere, so I removed that export.
  - Refactored the discord join modal a bit, felt like it's better inside the JoinModal folder as this is also a join modal, also removed the duplicated error processing utility function.
  - As Tomi suggested, I changed the wallet connection flow, so we display the network change modal instantly if the user is on an unsupported one.

### CODE REVIEW

File: src/components/web3Connection/WalletSelectorModal/WalletSelectorModal.tsx [hunk 1]
```diff
@@ -55,58 +58,66 @@ const Web3Modal = ({
   const handleOnboarding = () => onboarding.current?.startOnboarding()
 
   useEffect(() => {
-    if (active) {
+    if (active) closeModal()
+  }, [active, closeModal])
+
+  useEffect(() => {
```
Comment (KovJonas) [inline src/components/web3Connection/WalletSelectorModal/WalletSelectorModal.tsx:64]: This was a great idea too. Should we maybe show a similar modal when the user navigates to a community page which isn't on the user's currently selected network (e.g. when the user is on the Matic network, and they navigate to the "Ethane" community page)? Or maybe that would be too much, and the modal would just annoy the user?

**Review by dovalid — APPROVED** [review]
